image: golang:latest

variables:
  REPO_NAME: gitlab.com/sorenmat/seneferu
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/sorenmat/seneferu:latest
  POSTGRES_HOST: postgres
  POSTGRES_DB: seneferu
  CI_BUILD_REF_NAME: $CI_COMMIT_REF_NAME
  CI_BUILD_ID: $CI_JOB_ID
  CI_BUILD_REPO: $CI_REPOSITORY_URL
  CI_BUILD_REF: $CI_COMMIT_SHA

before_script:
  - mkdir -p $GOPATH/src/$REPO_NAME
  - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - validate
    - build
    - coverage
    - coverage-upload
    - release

#format:
#    stage: validate
#    script:
#      - go fmt ./...
#vet:
#  stage: validate
#  script:
#      - go vet ./...

#test:
#  stage: validate
#  services:
#    - postgres:latest
#  script:
#     - go test -race ./...

#compile:
#    stage: build
#    script:
#      - GOOS=linux CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/seneferu
#    artifacts:
#      untracked: true

#compile-js:
#  stage: build
#  image: node:9.2.0
#  script:
#    - cd $CI_PROJECT_DIR
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#    - js/


coverage:
  image: golang:1.10beta2-alpine
  stage: coverage
  services:
    - postgres:latest

  artifacts:
    paths:
    - coverage.txt

  script:
    - ls
    - go version
    - go test -coverprofile=coverage.txt -covermode=atomic ./...

coverage-upload:
  image: ubuntu
  stage: coverage-upload
  dependencies:
  - coverage
  script:
    - ls -la
    - apt update
    - apt install -y curl
    - echo ${CODECOV_TOKEN}
    - bash <(curl -s https://codecov.io/bash) -t d943264a-ca45-410e-a190-75d02601ffae
#
#
#release-image:
#  stage: release
#  image: docker:git
#  only:
#    - master
#  services:
#    - docker:dind
#  dependencies: 
#    - compile
#    - compile-js
#  script:
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker version
#    - cd $CI_PROJECT_DIR
#    - docker build -t registry.gitlab.com/sorenmat/seneferu:$CI_COMMIT_REF_NAME .
#    - docker push registry.gitlab.com/sorenmat/seneferu:$CI_COMMIT_REF_NAME
#
