pipeline:
  build:
    group: build
    image: golang:latest
    environment:
      - NAME=testing
    commands:
      - ls -la
      - go get -v -u
      - go build
      - go list ./... |  grep -v vendor | xargs go list -f '{{.ImportPath}}' | xargs -L 1 -n 1 -I '{#}' bash -c 'go test {#} -coverprofile=testing`date +%s`.cover'
      - docker build -t sorenmat/test:${HASH} .
